name: Gamev
description: oi
version: 0.1.0
author: rodoviajw#1888
main: rodovia.gamev.plugin.GamevPlugin

commands:
    gameraevento:
        aliases: [gev, gamera]
        usage: /<command> [create]
    gcheckpoint:
        aliases: [checkpoint, gcheckp]
        usage: /<command> [set <player> <evento> <id do checkpoint>]

