name: Gamev
description: oi
version: 0.1rc2
author: rodoviajw#1888
main: rodovia.gamev.plugin.GamevPlugin

commands:
    gameraevento:
        aliases: [gev, gamera]
        usage: /<command> [create]